### ISSUE TITLE
Priorities for Customisation

### ISSUE THREAD

**Issue by curran** [unhcr/dataviz-styleguide#37]
Attempting to create a prioritized list based on recent activity. Feel free to rearrange by dragging items.

 * [ ] Customising semantic h1/h2/h3/etc classes to be consistent with the text-styles in the guidelines #39
 * [ ] Document which classes map to which type of thing from the guidelines #40
 * [ ] Colors #30
 * [x] Customise radio buttons #38
 * [ ] Customise statistic #42
 * [x] Customise button #41

**Comment by curran** [comment]
Closing in favor of using Trello
